# Use an official Python runtime as a parent image
FROM python:3.8-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install django django-cors-headers

COPY backend/ /app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
